# Site settings
title: Leaf's Official Website
email: leafelectro@gmail.com
description: Leaf's Official Website
baseurl: "/leafelectro.com" # the subpath of your site, e.g. /blog/
url: "http://leafelectro.com" # the base hostname & protocol for your site
twitter_username: leafelectro
github_username:  leafelectro

# Build settings
markdown: kramdown
